CREATE TABLE `test`.`GRESTWP_OPTIONS` 
( `LNK_PRIVACY_TERMS` VARCHAR(1000) NOT NULL COMMENT 'Link al disclamer per la privacy' 
, `LNK_CONSENSUALS_TERMS` VARCHAR(1000) NOT NULL COMMENT 'Link al disclamer per il trattamento dei dati personali' 
, `LNK_PHOTO_TERMS` VARCHAR(1000) NOT NULL COMMENT 'Link al disclaimer per il consenso per le foto' ) 
ENGINE = InnoDB 
COMMENT = 'Tabella parametri del sistema grest';

CREATE TABLE `test`.`GRESTWP_EVENT` ( 
`id` INT NOT NULL AUTO_INCREMENT 
, `NAME` VARCHAR(255) NOT NULL 
, `NOTE` TEXT NOT NULL , `DATE_START` DATE NOT NULL 
, `DATE_STOP` DATE NOT NULL 
, `DATE_BOOK_START` DATE NOT NULL 
, `DATE_BOOK_STOP` DATE NOT NULL 
, `REFERENT_NAME` VARCHAR(255) NOT NULL 
, `REFERENT_MAIL` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`id`)) 
ENGINE = InnoDB 
COMMENT = 'Tabella dei grest (una per grest)';


CREATE TABLE `test`.`GRESTWP_WEEK` ( 
`ID` INT NOT NULL AUTO_INCREMENT 
, `ID_EVENT` INT NOT NULL 
, `NAME` VARCHAR(255) NOT NULL 
, `NOTE` TEXT NOT NULL 
, `DATE_START` DATE NOT NULL 
, `DATE_STOP` DATE NOT NULL 
, `PLACES` INT NOT NULL 
, PRIMARY KEY (`ID`)) 
ENGINE = InnoDB 
COMMENT = 'Tabella delle settimane di grest';



CREATE TABLE `test`.`GRESTWP_LAB` ( 
`ID` INT NOT NULL AUTO_INCREMENT 
, `ID_WEEK` INT NOT NULL 
, `NAME` VARCHAR(255) NOT NULL 
, `NOtE` TEXT NOT NULL 
, `PLACES` INT NOT NULL 
, PRIMARY KEY (`ID`)) 
ENGINE = InnoDB 
COMMENT = 'Tabella dei laboratori (per settimana)';


CREATE TABLE `test`.`GRESTWP_PARENTS` ( 
`ID` INT NOT NULL AUTO_INCREMENT 
, `ID_WP` INT NOT NULL COMMENT 'id del\'utente wordpress collegato' 
, `USER` VARCHAR(255) NOT NULL 
, `MAIL` VARCHAR(255) NOT NULL 
, `PHONE` VARCHAR(255) NOT NULL 
, `NOTE` TEXT NOT NULL 
, `PRIVACY_OK` INT NOT NULL COMMENT 'Accettazione INFORMATIVA AL TRATTAMENTO DEI DATI PERSONALI' 
, `DATA_OK` INT NOT NULL COMMENT 'Accettzione CONSENSO TRATTAMENTO DATI' 
, `PHOTO_OK` INT NOT NULL COMMENT 'Accettazione CONSENSO PER RIPRESE VIDEO/FOTO' 
, PRIMARY KEY (`ID`)) 
ENGINE = InnoDB 
COMMENT = 'Tabella registrazione genitore';


CREATE TABLE `test`.`GRESTWP_CHILD` ( 
`ID` INT NOT NULL AUTO_INCREMENT 
, `ID_PARENT` INT NOT NULL COMMENT 'Collegamento al genitore che lo registra' 
, `NAME` VARCHAR(255) NOT NULL 
, `SURNAME` VARCHAR(255) NOT NULL 
, `BIRTHDAY` DATE NOT NULL 
, `COD_FISCALE` VARCHAR(30) NOT NULL 
, `TAGLIA` VARCHAR(50) NOT NULL 
, `NOTE` TEXT NOT NULL , `PRIVACY_OK` INT NOT NULL COMMENT 'Accettazione INFORMATIVA AL TRATTAMENTO DEI DATI PERSONALI' 
, `DATA_OK` INT NOT NULL COMMENT 'Accettzione CONSENSO TRATTAMENTO DATI' 
, `PHOTO_OK` INT NOT NULL COMMENT 'Accettazione CONSENSO PER RIPRESE VIDEO/FOTO' 
, PRIMARY KEY (`ID`)) 
ENGINE = InnoDB 
COMMENT = 'Tabella dei ragazzi';


CREATE TABLE `test`.`GRESTWP_BOOKED` ( 
`ID` INT NOT NULL AUTO_INCREMENT 
, `ID_CHILD` INT NOT NULL 
, `ID_WEEK` INT NOT NULL 
, `ID_WEEK_LAB` INT NOT NULL COMMENT 'Laboratorio scelto' 
, `ID_LUNCH` INT NOT NULL COMMENT 'Pausa pranzo' 
, `ID_AFTERNOON` INT NOT NULL COMMENT 'Pomeriggio' 
, `EARLY_ENTRY` INT NOT NULL COMMENT 'Entrata anticipata' 
, `POSTPONED_EXIT` INT NOT NULL COMMENT 'Uscita posticipata' 
, `TRIP` INT NOT NULL COMMENT 'Se partecipa alla gita' 
, `NOTE` TEXT NOT NULL 
, `CANCELED` INT NOT NULL COMMENT '1 se la prenotazione è annullata' 
, PRIMARY KEY (`ID`)) 
ENGINE = InnoDB 
COMMENT = 'tabella delle prenotazioni';